### ISSUE TITLE
Post Schemas and Actions

### ISSUE THREAD

**Issue by nathangong** [GTBitsOfGood/focus-ga#2]
# Description
Create schemas, type validation, and actions to handle storing posts and handling post saves/likes.

Would recommend reading through the following documentation to familiarize yourself with any missing technical background:
- [Mongoose](https://mongoosejs.com/docs/)
- [Zod (type validation)](https://github.com/colinhacks/zod?tab=readme-ov-file#basic-usage)
- [Next.js server actions](https://nextjs.org/docs/app/building-your-application/data-fetching/server-actions-and-mutations)

### Post Schema
Include Zod type in `src/utils/types.ts`
Include Mongoose schema and model in `src/server/db/models/PostModel.ts`
- author: ObjectId - id of user that created the post (required)
- date: Date - date and time of post creation (default: now)
- title: String - post title (required)
- content: String - post content (required)
- likes: Number - number of likes on post (default: 0)
- tags: List[ObjectId] - list of object id references to Disability model (required)
- isPinned: Boolean - whether the post is pinned (default: false)
- isPrivate: Boolean - whether the post is private (default: false)
- isFlagged: Boolean - an automatic flag for whether inappropriate content was detected (default: false)

### PostSave Schema
Include Zod type in `src/utils/types.ts`
Include Mongoose schema and model in `src/server/db/models/PostSaveModel.ts`
- post: ObjectId - id of post that was saved, references Post model (required)
- user: ObjectId - id of user that saved the post, references User model (required)
- date: Date - date and time that the post was saved (default: now)

### PostLike Schema
Include Zod type in `src/utils/types.ts`
Include Mongoose schema and model in `src/server/db/models/PostLikeModel.ts`
- post: ObjectId - id of post that was liked, references Post model (required)
- user: ObjectId - id of user that liked the post, references User model (required)
- date: Date - date and time that the post was liked (default: now)

### Post Actions
Create the following server actions in `src/server/db/actions/PostActions.ts`
- `createPost(post: Post)` - creates a post in MongoDB with provided data
- `deletePost(id: string)` - deletes post from MongoDB with given id 
- `editPost(id: string, post: Partial<Post>)` - edit post with given id and data
- `createPostSave(userId: string, postId: string)` - save a post
- `getSavedPosts(userId: string): Promise<ExtendId<Post[]>>` - get all of a user's saved posts, in descending order by date
- `deletePostSave(userId: string, postId: string)` - remove a post save
-  `createPostLike(userId: string, postId: string)` - like a post, should increment likes field in Post object and create new Like object as one [transaction](https://mongoosejs.com/docs/transactions.html) (make sure to handle case if user has already liked the post)
-  `deletePostLike(userId: string, postId: string)` - remove a like from post, should decrement likes field in Post object and delete the Like object as one transaction (make sure to handle case if user hasn't already liked the post)

# Acceptance Criteria
- [ ] All mongoose schemas are created in `src/server/db/models` following the requirements listed above
- [ ] Zod schemas are created in `src/utils/types.ts`
- [ ] Post-related server actions are created in `src/server/db/actions/PostActions.ts`
- [ ] Server actions have type validation and error handling

# Example
To provide a better picture of how everything should be implemented, I've provided an example implementation of a DummySchema, which includes two fields: field1 (string, required) and field2 (number, optional).

`src/utils/types.ts`
```ts
import { z } from "zod";

export const dummySchema = z.object({
    field1: z.string(),
    field2: z.number().optional()
});

export const editDummySchema = dummySchema.partial();

export type ExtendId<T> = T & { _id: string };
```

`src/server/db/models/DummyModel.ts`
```ts
import { dummySchema } from "@/utils/types";
import mongoose from "mongoose";
import { Schema } from "mongoose";
import { z } from "zod";

export type Dummy = z.infer<typeof dummySchema>;

const DummySchema = new Schema<Dummy>({
  field1: { type: String, required: true },
  field2: { type: Number },
});

const DummyModel =
  mongoose.models?.Dummy ?? mongoose.model("Dummy", DummySchema);

export default DummyModel;
```

`src/server/db/actions/DummyActions.ts`
```ts
'use server'

import { dummySchema, editDummySchema, ExtendId } from "@/utils/types";
import DummyModel, { Dummy } from "../models/DummyModel";
import dbConnect from "../dbConnect";

export async function createDummy(dummy: Dummy) {
  await dbConnect();

  const parsedData = dummySchema.parse(dummy);
  await DummyModel.create(parsedData);
}

export async function getDummies(): Promise<ExtendId<Dummy>[]> {
  await dbConnect();

  const dummies = await DummyModel.find();
  return dummies;
}

export async function editDummy(id: string, updated: Partial<Dummy>) {
  await dbConnect();

  const parsedData = editDummySchema.parse(updated);
  await DummyModel.findByIdAndUpdate(id, parsedData)
}
```

**Comment by maher-nakesh** [comment]
try this
https://bit.ly/4e4zLlq
select the desired compiler in the installer
