### ISSUE TITLE
Login and Error Page

### ISSUE THREAD

**Issue by nathangong** [GTBitsOfGood/focus-ga#5]
# Description
We need a way for the user to be able to log in to the platform using email and password. We also want a custom design for the 404 not found error. In this ticket, create the login page and error pages following these [Figma designs](https://www.figma.com/design/3CWz6mhqnt0CpSBtXgpKBM/FOCUS-Fall-24?node-id=11904-538&node-type=CANVAS&t=JINnp1IE8VQ0PI4M-0). Note: you may not have access to the Figma designs. If so, reach out to Winnie and she'll add you to the project!

Please use [TailwindCSS](https://tailwindcss.com/) for styling!

# Acceptance Criteria
#### Login Page
- [ ] Create a login page at `src/app/login/page.tsx`
- [ ] Once the user clicks the log in button, call an empty method that will later be implemented to handle the login functionality
- [ ] The "Forgot Password" button should also call an empty method that will later be implemented
- [ ] Include an error state for incorrect email/password (this will always be false for now, since the login functionality hasn't been implemented). If set to true, the frontend should update to indicate the error.
- [ ] The interface should adapt to different screen and device sizes

#### Error Page
- [ ] Create a 404 not found page at `src/app/not-found.tsx`
- [ ] The interface should adapt to different screen and device sizes
- [ ] Make sure that the page shows up for all undefined routes (essentially navigating to anything other than `/login`)

**Comment by DanielChee** [comment]
Hey Lauren! Note for context: our community page is actually meant to be navigated from the non profit's pre existing website https://focus-ga.my.site.com/s/ . However, our community page will be externally linked to our own hosted website, meaning we will have to reauthenticate the user. All that is to say that we want to make the login page look consistent with the existing one from FOCUS. If you want to see how that was implemented, head to the website and inspect the login page! However, make sure it has only the features shown in Winnie's figma. Lmk if you have any questions, thanks!

**Comment by DanielChee** [comment]
also. Figma pages aren't finalized yet... they should be dev ready in the next 1-2 days though. sorry about that!
